services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=xprice'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - '9411'
